Add note about context menu to top tags options settings.
metabrainz/picard-docs pull request #140
Opened 2021-12-14 18:47 UTC by rdswift

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

There was nothing in the documentation regarding the context menu items that allows showing the changed tags at the top of the list.  See the discussion in the [Community Forum](https://community.metabrainz.org/t/how-to-sort-the-tag-appearance-in-the-metadata-pane-in-picard/563528).

### Description of the Change

Add note about context menu to top tags options settings.

### Additional Action Required

Update translation files.

2021-12-15 20:35 UTC, phw requested changes
Yes, this definitely should get documented. I just would word it a bit differently.

2021-12-15 20:35 UTC, phw commented on config/options_interface_top_tags.rst
> +   and enable :menuselection:`"Show Changes First"` in the context menu.
I find this a bit misleading. The default of title, artist, album, ... can be directly changed with the top tags options above. "Show changes first" then is an additional option, which will then show the changes first regardless of the top tags. What about something like:

> By default, Picard will display the top tags configured here first in the list. If you enable :menuselection:`"Show Changes First"` in the context menu of the metadata pane the tags with changes will always be displayed first in the list, followed by the remaining top tags and other tags.

2021-12-15 21:09 UTC, rdswift commented on config/options_interface_top_tags.rst
> +   and enable :menuselection:`"Show Changes First"` in the context menu.
Thanks for this.  I completely misunderstood, and what I had written clearly didn't make sense.  This is much better.

2021-12-16 10:08 UTC, phw approved these changes
Great, LGTM!

2021-12-16 10:09 UTC, merged