Add documentation of the use of EAC / XLD logs for CD lookup
metabrainz/picard-docs pull request #154
Opened 2022-01-29 18:53 UTC by rdswift

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

Changes in https://github.com/metabrainz/picard/pull/2048 added the ability to use an EAC or XLD ripper log file to lookup a release.

### Description of the Change

Add documentation of the use of EAC / XLD logs for CD lookup.

### Additional Action Required

Update translation files.

2022-01-30 10:21 UTC, phw requested changes
Thanks a lot for tackling this. Just noticed the description is unclear for how results are displayed, also in existing disc lookup description.

And maybe we should also link to the disc ID lookup tutorials from https://picard-docs.musicbrainz.org/en/usage/attach_disc_id.html ?

2022-01-30 10:21 UTC, phw commented on workflows/workflow_extractor_log.rst
> +   If there is only one release that matches the disc id for your disc, it will be loaded automatically.  Before
That's actually not accurate. It will always display the CD lookup dialog, even with only a single results. So users can verify the match and e.g. submit the disc ID if it does not match.

I think we should change this description to always describe the workflow via the dialog, also on https://picard-docs.musicbrainz.org/en/workflows/workflow_cd.html . We can show https://picard-docs.musicbrainz.org/en/_images/cd_lookup_1.png here.

2022-01-30 11:57 UTC, phw commented
I extended the functionality to also support Whipper logs in #2056. The UI is the same, it just extends the menu entry to be "From EAC / XLD / Whipper log file..."

2022-01-30 16:45 UTC, rdswift commented on workflows/workflow_extractor_log.rst
> +   If there is only one release that matches the disc id for your disc, it will be loaded automatically.  Before
I agree.  Changes made.

2022-02-12 10:01 UTC, phw approved these changes

2022-02-12 10:01 UTC, merged