Improve url remapping tests
metabrainz/picard-docs pull request #165
Opened 2022-03-28 23:36 UTC by rdswift

### Summary

This is a…

- [x] Correction
- [ ] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [x] Other

### Reason for the Change

Improve url remapping to try to avoid 404s.  Current tests and remapping did not properly handle some cases.

### Description of the Change

Improve automatic url remapping:

- Test and correct invalid version number such as 'v2.63' rather than 'v2.6' and to add missing 'v' if necessary.  Automatically redirect to the latest version if an invalid `major.minor` such as '99.99' is provided when the latest release is '2.7'.

- Automatically try to serve a language matching the preferred languages in the user's browser settings if there is no language specified in the url.  For example, `https://picard-docs.musicbrainz.org/variables/tags_basic.html` will be served as `https://picard-docs.musicbrainz.org/fr/variables/tags_basic.html` if the user's browser language preference is French.

- Automatically replace unsupported languages with the default language.  For example, `https://picard-docs.musicbrainz.org/tr/variables/tags_basic.html` will be served as `https://picard-docs.musicbrainz.org/en/variables/tags_basic.html` if there is no Turkish translation available.

- Automatically correct language and version number entered in the wrong order (should be version before language).  For example, `https://picard-docs.musicbrainz.org/en/2.63/variables/tags_basic.html` will be corrected to `https://picard-docs.musicbrainz.org/v2.6/en/variables/tags_basic.html`.

### Additional Action Required

None.

2022-03-28 23:40 UTC, rdswift commented
This automatic redirection functionality can be tested at [https://picard-docs-dev.rsds.ca/](https://picard-docs-dev.rsds.ca/).

2022-03-29 06:29 UTC, phw requested changes

2022-03-29 06:29 UTC, phw commented on 404_template.html
> +      const re_version_b = /^v?([0-9]+\.[0-9])/;
This would actually fail once we reach version 2.10. I think `[0-9]+` was the better test for the second number.

It is unlikely currently, because I'd really want to start version 3.0 in the course of this year, so either 2.8 will be the last 2.x version, or maybe there will be a 2.9. But it would be no mistake to consider this versioning already.

2022-03-29 19:04 UTC, rdswift commented on 404_template.html
> +      const re_version_b = /^v?([0-9]+\.[0-9])/;
Good catch.  I don't know what I was thinking when I changed that.

After some additional testing, I was able to make the check a bit more flexible in terms of matching when extra information was provided.  For example, if the version portion of the url is provided as `v2.6.3` it will now match `v2.6` rather than not match anything and default to the latest version.

2022-04-30 11:56 UTC, phw approved these changes

2022-04-30 17:57 UTC, merged