added -s, --stand-alone-instance
metabrainz/picard-docs pull request #174
Opened 2022-06-27 18:04 UTC by skelly37

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change
https://github.com/metabrainz/picard/pull/2116 will introduce new flag

### Description of the Change
Added the new flag

### Additional Action Required
Nope.

2022-06-27 18:04 UTC, skelly37 commented
ping: @rdswift, since you were interested.

2022-06-27 18:16 UTC, rdswift commented on appendices/command_line.rst
> +   force create new Picard instance
Minor suggested change in the wording...  Perhaps "force Picard to create a new instance" may be a bit clearer?

2022-06-28 08:23 UTC, skelly37 commented on appendices/command_line.rst
> +   force create new Picard instance
Okay, works for me, I'll change it in the Picard PR too.

2022-06-28 08:24 UTC, skelly37 commented on appendices/command_line.rst
> +   force create new Picard instance
I'll add `independent`, too, to signalize that it won't communicate with other processes.

2022-07-09 06:19 UTC, skelly37 commented
Should we include a warning about the pipe error we’re leaving unsolved for now? i.e. unexitable Picard  after removing the pipe file manually on Unix.

2022-07-21 11:06 UTC, atj reviewed
Some minor suggestions, most of which are subjective so I won't be offended if they are ignored!

2022-07-21 11:06 UTC, atj commented on appendices/command_line.rst
> +   location of the configuration file to use (starts a stand-alone instance)
Normally in help output you would write it something like this:

```suggestion
   location of the configuration file to use (implies ``--stand-alone-instance``)
```

2022-07-21 11:06 UTC, atj commented on getting_started/starting.rst
> +Important note: If Picard's inter-process-communication file (named in the following way: $PICARD_NAME_v$PICARD_VERSION_pipe_file) gets removed, you will not be able to exit nicely and will have to f
Suggested improved formatting / wording:

```suggestion
.. note::

Picard's stand-alone mode is implemented via the use of an inter-process-communication (IPC) file, which will be named according to the following format: ``$PICARD_NAME_v$PICARD_VERSION_pipe_file``. If this IPC file is deleted, Picard will not exit cleanly and will have to be forcefully terminated. This may be handled better in the future, however it is strongly suggested that users do not manually interact with this file.
```

2022-07-21 11:22 UTC, skelly37 commented on getting_started/starting.rst
> +
Actually, I don't know .rst and just try to help with writing the text. @rdswift I leave you with the quesiton

2022-07-21 14:46 UTC, skelly37 commented
I think we need an additional appendix documenting the new `mbid://`.

Basically it's:

`mbid://<entity-type>/<mbid>`

2022-07-25 15:24 UTC, rdswift commented on appendices/command_line.rst
> +   the file(s), URL(s) and MBID(s) to load
Should we include a brief description of the formats of the inputs?  Most people will probably understand the files and URLs, but not the required format for MBIDs.

2022-09-04 15:43 UTC, rdswift requested changes

2022-09-04 15:43 UTC, rdswift commented on getting_started/starting.rst
> +already running.  If the same version is already running, any files or directories specified
```suggestion
When the program is started, it checks to see if there is another instance of that version, configuration file and plugin startup status ``-P``
already running.  If the same version is already running, any files or directories specified
```

2022-09-04 15:43 UTC, rdswift commented on getting_started/starting.rst
> +- Windows portable instances always start as stand-alone by virtue of them using a different configuration file location than the standard location used for a desktop version of the program.
```suggestion
Instances started with command-line argument ``-s / --stand-alone`` always start as stand-alone.
```

The behavior has changed in https://github.com/metabrainz/picard/pull/2139 so this may need to be updated.

2022-09-04 15:44 UTC, skelly37 commented on appendices/command_line.rst
> +   the file(s), URL(s) and MBID(s) to load
Agreed

2022-09-04 15:46 UTC, skelly37 commented
I'll leave a TODO list later to sum up what still has to be done

2022-09-04 17:45 UTC, skelly37 commented
TODO:

- [ ] allowed URIs (positional arguments)
- [ ] list of commands
- [ ] re-read the diff to see if it is still up to date

@rdswift I can write most (if not all) of it but I'm bad at .rst. My idea is that I will send you my notes in markdown, e.g. via e-mail, and you will (kindly please :) ) help me with proper formatting

2022-09-04 18:52 UTC, rdswift commented
> @rdswift I can write most (if not all) of it but I'm bad at .rst. My idea is that I will send you my notes in markdown, e.g. via e-mail, and you will (kindly please :) ) help me with proper formatting

That's fine with me.  I appreciate whatever you can provide in terms of description of the new functionality.  Thanks.

2022-09-06 19:36 UTC, skelly37 commented
Positional arguments documentation:
---
In Picard one can pass 3 types of positional arguments:
- file:
  - relative path: will be auto-converted to an absolute path, where the current working directory is this path's parent
  - absolute path
  - `file://` URI
- supported URL (the same ones that work for drag'n'drop in GUI mode)
  - `http://` URI
  - `https://` URI 
- MBID URI
  - `mbid://<entity-type>/<mbid>`
  - Examples:
    - `mbid://release/dbd0ce67-cae6-33eb-8f5a-1143a30c2353`
    - `mbid://artist/83d91898-7763-47d7-b03b-b92132375c47`

2022-09-06 20:24 UTC, skelly37 commented
Remote commands
---
## General

- Picard remote process handling consists of 2 steps:
  1) It tries to pass commands to execute to an existing instance,
  2) If the commands were not received, it starts a new app that will process the command pipeline.
- Commands are case-insensitive.
- Commands are processed in the order they were provided.

## Usage
`picard -e <command> <arg(s)>`

## List of available commands
- `CLUSTER`
Cluster all files in the cluster pane.

- `FINGERPRINT`
Calculate acoustic fingerprints for all (matched) files in the album pane.

- `FROM_FILE <absolute path>`
Load command pipeline from the provided absolute path.
  - `#`-prefixed comments are accepted.
  - 1 line per 1 command, a single line should contain as much as single `picard -e <command> <argstring>` call.

- `LOAD <MBID/URL/absolute path(s)>`
Load one or more provided arguments to Picard.
  - Basically an equivalent of the positional arguments but it can be placed: 
    - anywhere in the `picard` call,
    - in the command pipeline files.
  - NOTE: LOAD does not support passing remote commands.

- `LOG_CLEAR`: TODO
Clear the Picard logs.

- `LOG_DUMP <absolute path>`: TODO
Save the Picard logs to the provided path.

- `LOOKUP`
Lookup all clusters in the cluster pane.

- `LOOKUP_CD <device/log file>`
Read CD from the selected drive and lookup on MusicBrainz.
Without argument, it defaults to the first (alphabetically) available disc drive.

- `QUIT`
Exit the running instance of Picard.

- `REMOVE <absolute path to 1 or more files>`
Remove the file from Picard. Do nothing if no arguments provided.

- `REMOVE_ALL`
Remove all files form Picard.

- `REMOVE_EMPTY`
Remove all empty clusters and albums.

- `REMOVE_SAVED`
Remove all saved releases from the album pane.

- `REMOVE_UNCLUSTERED`
Remove all unclustered files from the cluster pane.

- `SAVE_MATCHHED`
Save all matched releases from the album pane.

- `SAVE_MODIFIED`
Save all modified files from the album pane.

- `SCAN`
Scan all files in the cluster pane.

- `SHOW`
Make the running Picard instance the currently active window.

- `SUBMIT_FINGERPRINTS`
Submit outstanding acoustic fingerprints for all (matched) files in the album pane.

2022-11-06 17:07 UTC, rdswift commented
> * `LOOKUP`
>   Lookup all clusters in the cluster pane.

Note that this has been changed in https://github.com/metabrainz/picard/pull/2167

2022-11-30 18:09 UTC, rdswift requested changes
@skelly37 this will need to be updated to include the changes being made in https://github.com/metabrainz/picard/pull/2173 which I can do (as well as including the RST changes for the other text you provided), but I think that you will need to remove the DRAFT designation on this PR and allow changes by maintainers.

Alternatively, if you want me to take over and complete all the remaining changes, I can clone your work so far, make the changes and additions, and then submit a new PR based on the updated clone.  We can then close this PR.

In either case, I still want to make sure that you're credited for your contributions in the documentation.  Thanks.

2022-12-02 19:12 UTC, skelly37 commented
@rdswift Apologies for the response delay. I’d suggest to go with the second option, as you’d have full control over the branch. Let me know when to close this PR, thanks in advance.

2022-12-03 02:55 UTC, rdswift commented
This PR  has been combined into https://github.com/metabrainz/picard-docs/pull/178

2022-12-03 02:55 UTC, closed without merging