Add fre:ac to logs parsed
metabrainz/picard-docs pull request #176
Opened 2022-09-30 17:27 UTC by rdswift

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [x] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

Parsing of **fre:ac** logs is being added to version 3 of Picard in https://github.com/metabrainz/picard/pull/2158.

### Description of the Change

Update the list of ripper logs that Picard can process for lookup.  Also some minor refactoring to clarify the index entries for the page.

### Additional Action Required

Once merged, the translation files will need to be updated.

2022-09-30 19:14 UTC, phw commented
Cool, thanks for taking care of this. There is also dBpoweramp logs supported now which I added recently to Picsrd

2022-09-30 19:26 UTC, phw requested changes
Looks good to me, just should also include the changes from https://github.com/metabrainz/picard/pull/2151

2022-09-30 19:26 UTC, phw commented on usage/retrieve_lookup_cd_steps.txt
>     The CD TOC will be calculated and sent to MusicBrainz. Alternately, you can use an EAC, XLD or Whipper ripper log file
I would mention free:ac and dBpoweramp here

2022-09-30 19:26 UTC, phw commented on usage/retrieve_lookup_cd_steps.txt
> +   to lookup the CD using the :menuselection:`"Tools --> Lookup CD --> From EAC / XLD / Whipper / fre:ac log file..."` command. This
I renamed this menu entry in https in https://github.com/metabrainz/picard/pull/2151 to be just "From CD ripper log file..." because it started to get too much with listing all the tools

See https://github.com/metabrainz/picard/pull/2151

2022-09-30 19:26 UTC, phw commented on workflows/workflow_extractor_log.rst
> +`fre:ac <https://www.freac.org>`_ for multiple platforms.  Because the log files of these
dBpoweramp https://dbpoweramp.com/ for macOS and Windows

2022-09-30 19:26 UTC, phw commented on workflows/workflow_extractor_log.rst
> +   :menuselection:`"Tools --> Lookup CD --> EAC / XLD / Whipper / fre:ac log files..."` command. This will open a
"From CD ripper log file..."

2022-09-30 20:09 UTC, rdswift commented on usage/retrieve_lookup_cd_steps.txt
>     The CD TOC will be calculated and sent to MusicBrainz. Alternately, you can use an EAC, XLD or Whipper ripper log file
To avoid listing all the supported rippers multiple times (and maintining multiple lists), I listed them (with links) in `workflows/workflow_extractor_log.rst` and then linked this page as "supported ripper log file".  I'm wondering if it might be better to add another page (likely in the appendices) with the list and link to this from both `workflows/workflow_extractor_log.rst` and `usage/retrieve_lookup_cd_steps.rst`.  What do you think?

2022-10-01 06:03 UTC, phw commented on usage/retrieve_lookup_cd_steps.txt
>     The CD TOC will be calculated and sent to MusicBrainz. Alternately, you can use an EAC, XLD or Whipper ripper log file
Yes, that sounds like a good idea. Or maybe an entry in the FAQs? Something we can link to in any case

2022-10-01 17:48 UTC, rdswift commented on usage/retrieve_lookup_cd_steps.txt
>     The CD TOC will be calculated and sent to MusicBrainz. Alternately, you can use an EAC, XLD or Whipper ripper log file
I really like your suggestion of putting the list as a new entry in the FAQ section.  The list has been moved there, and links to this list have been added to `workflows/workflow_extractor_log.rst` and `usage/retrieve_lookup_cd_steps.rst`.

2022-11-24 20:31 UTC, phw reviewed
This sounds correct. And is a good way handling all these different tools. Only change would be as I commented to have the tools list point out that it is available with Picard 2.9, not 2.8.

2022-11-24 20:31 UTC, phw commented on faq/faq_file_formats.rst
> +As of version 2.8, Picard supports the use of log files produced by popular CD file rippers for looking up a release. Because the log
So this will be the list for Picard 2.9. For current 2.8 it would be this list except for dbPoweramp and fre:ac

2022-11-25 15:42 UTC, rdswift commented on faq/faq_file_formats.rst
> +As of version 2.8, Picard supports the use of log files produced by popular CD file rippers for looking up a release. Because the log
> So this will be the list for Picard 2.9. For current 2.8 it would be this list except for dbPoweramp and fre:ac

Good catch.  I've updated the version number to 2.9 and set the milestone to 2.9 as well.

2022-11-25 15:47 UTC, phw approved these changes

2022-12-03 20:58 UTC, rdswift commented
Removed the translation file updates to avoid ongoing merge conflicts.  Will need to do a general update of the translation files once all of the v2.9 changes have been merged into the `master` branch.

2022-12-04 17:49 UTC, phw commented
@rdswift That's the main reason why we never handle translation file updates in pull requests on main picard repo, and actually that is how I handle this in other projects as well. Updating the .po files in two separate branches is almost guaranteed to cause merge conflicts. Furthermore those are not easy to solve. Best approach is usually to just regenerate the files in a merged branch and add the missing translations. Or just manually merge with a best effort to keep all changes, and then also fully regenerate the .po files again.

 So IMHO it is easier to ignore the translations in merge requests and only update translations on master.

2022-12-06 16:46 UTC, merged