Update variables_file.rst
metabrainz/picard-docs pull request #218
Opened 2024-01-16 11:33 UTC by nullHawk

Added _filesize variable as mentioned in "https://github.com/metabrainz/picard/pull/2361"

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

Added _filesize variable as mentioned in "https://github.com/metabrainz/picard/pull/2361"

### Description of the Change

### Additional Action Required

2024-01-16 12:21 UTC, zas requested changes
AFAIK, units should not be capitalized but if they are named after a proper name (like Celsius). Even if abbreviation is (B for byte, but that's because b is used for bit).

2024-01-16 12:21 UTC, zas commented on variables/variables_file.rst
> +   Size of the file in Bytes.
```suggestion
   Size of the file in bytes.
```

2024-01-16 12:22 UTC, phw requested changes

2024-01-16 12:22 UTC, phw commented on variables/variables_file.rst
> +**_filesize**
Please add a blank line before the `**_filesize**`

2024-01-16 13:47 UTC, rdswift commented
@nullHawk, please also add your name to the list of contributors in `about_picard/acknowledgements.rst`.  Note that the ordering is alphabetical by surname.

2024-01-16 15:34 UTC, nullHawk commented
> AFAIK, units should not be capitalized but if they are named after a proper name (like Celsius). Even if abbreviation is (B for byte, but that's because b is used for bit).

Thank you for mentioning it, I will keep that in mind from now onwards

2024-01-16 15:34 UTC, nullHawk commented
> @nullHawk, please also add your name to the list of contributors in `about_picard/acknowledgements.rst`. Note that the ordering is alphabetical by surname.

Ok, got it

2024-01-18 22:30 UTC, zas approved these changes

2024-01-20 17:19 UTC, phw approved these changes

2024-01-20 17:19 UTC, merged

2024-01-20 17:20 UTC, phw commented
Thanks again, merged